# https://github.com/INTI-CMNB/KiBot/tree/dev/tests/yaml_samples

kibot:
  version: 1

preflight:
  draw_stackup: true
  check_zone_fills: true
  erc:
    category: 'schematics'
    dir: 'reports'
    format: 'HTML, RPT'
    output: 'schematic electrical-rule-check report.%x'
  drc:
    category: 'pcb'
    dir: 'reports'
    format: 'HTML, RPT'
    output: 'PCB design-rule-check report.%x'

outputs:
# Schematic outputs
  - name: 'Schematic PDF'
    type: pdf_sch_print
    dir: 'schematic'

  - name: 'Schematic SVG'
    type: svg_sch_print
    dir: 'schematic'

# BOM outputs
  - name: 'Interactive BOM'
    type: ibom
    dir: 'bom'
    category: 'bom'


# PCB outputs
  - name: 'print_front'
    dir: 'pcb'
    type: pcb_print
    options:
      output: 'front.%x'
      format: 'PNG'
      pages:
        - layers:
            - layer: F.Cu
            - layer: F.Mask
              color: '#14332440'
            - layer: Edge.Cuts
              color: "#004040"
          page_id: F_Cu_color

  - name: 'print_back'
    dir: 'pcb'
    type: pcb_print
    options:
      output: 'back.%x'
      format: 'PNG'
      pages:
        - layers:
            - layer: B.Cu
            - layer: B.Mask
              color: '#14332440'
            - layer: User.Drawings
            - layer: User.Comments
          sort_layers: true
          monochrome: true
          mirror: true
          sheet_reference_color: "#A02020"

  - name: '3D model - .step'
    type : step
    dir: 'pcb'

  - name: 'renders'
    type: blender_export
    dir: 'pcb'
    options:
      add_default_light: true
      light:
        type: 'SUN'
      render_options:
        transparent_background: true
        samples: 10
      point_of_view:
        rotate_x: 30
        rotate_z: -20
      fixed_auto_camera: false
      auto_camera_z_axis_factor: 1.5
      default_file_id: '_%03d'
      outputs:
        - type: render

