# https://github.com/INTI-CMNB/KiBot/tree/dev/tests/yaml_samples

kibot:
  version: 1

preflight:
  erc:
    dir: 'reports'
  drc:
    dir: 'reports'
  check_zone_fills: true

outputs:
  - name: 'Schematic PDF'
    type: pdf_sch_print
    dir: 'pdf'

  - name: 'Schematic SVG'
    type: svg_sch_print
    dir: 'svg'

  - name: 'PCB Print'
    type: pcb_print
    dir: 'svg'
    options:
      format: 'svg'
      pages:
        layers: 'copper'

  - name: 'Interactive BOM'
    type: ibom
    dir: 'bom'

  - name: '3D model - .step'
    type : step
    dir: 'step'

  - name: 'renders'
    type: blender_export
    dir: 'render'
    options:
      add_default_light: true
      light:
        type: 'SUN'
      render_options:
        transparent_background: true
        samples: 10
      point_of_view:
        rotate_x: 30
        rotate_z: -20
      fixed_auto_camera: false
      auto_camera_z_axis_factor: 1.5
      default_file_id: '_%03d'
      outputs:
        - type: render

  - name: PcbDraw
    comment: "PcbDraw font test"
    dir: 'test'
    type: pcbdraw
    options:
      format: png

  - name: 'print_front'
    comment: "Font and colors"
    dir: 'test'
    type: pcb_print
    options:
      plot_sheet_reference: false
      scaling: 3
      format: PNG
      pages:
        - layers: [F.Cu, Edge.Cuts]