name: "KiCad DRC / ERC Check"
on:
  workflow_dispatch:
  push:
    branches: [main, develop]

jobs:
  drcerc:
    name: Run DRC and ERC, Export Schematic as PDF
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env: 
      CI_COMMIT_MESSAGE: add workflow generated files
      CI_COMMIT_AUTHOR: CD Workflow

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: run KiBOT export
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          additional_args: '--verbose'
          config: config.kibot.yaml
          dir: outputs
          schema: 'BME688-ML-V1-PCB.kicad_sch'
          board: 'BME688-ML-V1-PCB.kicad_pcb'

      - name: GIT Commit CI Artifacts
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "pascal.roobrouck@gmail.com"
          git add .
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push